
server.port=8081


spring.cloud.config.enabled=false

spring.application.name=media-service
spring.main.web-application-type=reactive



eureka.client.enabled=false


spring.r2dbc.url=r2dbc:postgresql://localhost:5432/media_db
spring.r2dbc.username=postgres
spring.r2dbc.password=password
spring.r2dbc.pool.enabled=true


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8088/realms/your-realm

spring.minio.url=http://127.0.0.1:9000
spring.minio.access-key=minioadmin
spring.minio.secret-key=minioadmin
spring.minio.bucket=media
spring.minio.check-bucket=true
spring.minio.create-bucket=true


management.endpoints.web.exposure.include=health,prometheus


logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.org.springframework.r2dbc=DEBUG



springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.info.title=Media Service API
springdoc.info.description=API for managing media files (uploads, downloads, etc.)
springdoc.info.version=v1.0.0
springdoc.info.contact.name=Votre Nom
springdoc.info.contact.email=votre.email@example.com


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/migrations/master.xml