
server.port=${SERVER_PORT:8081}


spring.cloud.config.enabled=false

spring.application.name=media-service
spring.main.web-application-type=reactive
#logging.level.org.springframework.boot.autoconfigure=DEBUG


eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}


spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/media_db}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:postgres}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:postgres}
spring.r2dbc.pool.enabled=${SPRING_R2DBC_POOL_ENABLED:true}
# Nombre de connexions ouvertes au démarrage
spring.r2dbc.pool.initial-size=1
# MAX connexions simultanées vers PostgreSQL
spring.r2dbc.pool.max-size=5
# Temps max d’attente pour obtenir une connexion
spring.r2dbc.pool.max-acquire-time=30s
# Libère les connexions inutilisées
spring.r2dbc.pool.max-idle-time=30m
# Recycle les connexions (évite les leaks)
spring.r2dbc.pool.max-life-time=10m
# Retry si le pool est saturé
spring.r2dbc.pool.acquire-retry=3
# Vérification de la connexion
spring.r2dbc.pool.validation-query=SELECT 1

# DATABASE — Liquibase (DDL : CREATE TABLE, ALTER, migrations)
# ------------------------------------------------------------------
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:yowyob}
spring.liquibase.user=${DB_LIQUIBASE_USERNAME}
spring.liquibase.password=${DB_LIQUIBASE_PASSWORD}


#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8088/realms/your-realm

spring.minio.url=${SPRING_MINIO_URL:http://127.0.0.1:9000}
spring.minio.access-key=${SPRING_MINIO_ACCESS_KEY:minioadmin}
spring.minio.secret-key=${SPRING_MINIO_SECRET_KEY:minioadmin}
spring.minio.bucket=${SPRING_MINIO_BUCKET:media}
spring.minio.check-bucket=${SPRING_MINIO_CHECK_BUCKET:true}
spring.minio.create-bucket=${SPRING_MINIO_CREATE_BUCKET:true}
app.public-url=${APP_PUBLIC_URL:https://media-service.pynfi.com}


management.endpoints.web.exposure.include=health,prometheus


logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.org.springframework.r2dbc=DEBUG



springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.info.title=Media Service API
springdoc.info.description=API for managing media files (uploads, downloads, etc.)
springdoc.info.version=v1.0.0
springdoc.info.contact.name=Votre Nom
springdoc.info.contact.email=votre.email@example.com
server.forward-headers-strategy=framework


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/migrations/default/master.xml

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/media_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
